config/routes.rb
Airbnb::Application.routes.draw do
  devise_for :users
  root :to => 'accomodations#index'
  resources :users
  resources :accomodations
  resources :bookings
end

app/models/accomodation.rb
class Accomodation < ActiveRecord::Base
  has_many :bookings
  has_many :users, through: :bookings

  validates :location, :presence => true
  validates :description, :presence => true
  validates :price, :presence => true
  validates :rooms, :presence => true
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :accomodation

  validates :check_in, :presence => true
  validates :check_out, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :accomodations, through: :bookings

  validates :name, :presence => true

end

app/controllers/accomodations_controller.rb
class AccomodationsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_filter :find_accomodation, only: [:show]

  def index
    @accomodations = Accomodation.all
  end

  def show
  end

  def create
    @accomodation = Accomodation.new(accomodation_params)
    if @accomodation.save
      @accomodation.user_id = current_user.id
      flash[:notice] = "Listing added successfully"
      respond_to do |format|
        format.html { redirect_to user_path(current_user.id) }
        format.js
      end
    else
      alert[:notice] = "Listing not saved"
      redirect_to user_path(@user_id)
    end
  end

  private

  def find_accomodation
    @accomodation = Accomodation.find(params[:id])
  end

  def accomodation_params
    params.require(:accomodation).permit(:location, :description, :price, :rooms, :cancellation_fee, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @accomodation = Accomodation.find_by(params[:id])
    @booking = Booking.new
  end

  def create
    @accomodation = Accomodation.find_by(params[:id])
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.accomodation_id = @accomodation.id
    if @booking.save
      flash[:notice] = "Room Booked!"
      redirect_to accomodations_path
    else
      alert[:notice] = "Room not booked, please try again"
      render("new")
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @accomodation = Accomodation.new
    @accomodations = Accomodation.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accomodations/_accomodation.html.erb
<ul class="accomodations-ul">
   <li class="accomodations-li accomodations-header"><%= link_to accomodation.location, accomodation_path(accomodation.id) %></li>
    <ul>
      <li class="accomodations-li"><%= accomodation.description %></li>
      <li class="accomodations-li"><%= accomodation.price %></li>
    </ul>
</ul>

app/views/accomodations/_form.html.erb
<%= form_for @accomodation do |f| %>
  <% if @accomodation.errors.any? %>
      <div class="error_messages">
        <h2 class="error">Form is invaid</h2>
        <ul>
          <% @accomodation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group"><%= f.label :location %><br />
  <%= f.text_field :location, autofocus: true %></div>

  <div class="form-group"><%= f.label :description %><br />
  <%= f.text_field :description, autofocus: true %></div>

  <div class="form-group"><%= f.label :price %><br />
    <%= f.text_field :price %></div>
  <div class="form-group"><%= f.label :rooms %><br />
    <%= f.text_field :rooms%></div>

  <div class="form-group"><%= f.label :cancellation_fee %><br />
    <%= f.text_field :cancellation_fee %></div>

  <div><%= f.submit "Post Listing", :class => "btn btn-default" %></div>
<% end %>

app/views/accomodations/create.js.erb
<% if @accomodation.save? %>
  $('.accomodations-list').prepend('<%= j render(@accomodation) %>');
<% end %>

app/views/accomodations/index.html.erb
<h1>Reserve Today! </h1>
<ul class="accomodations-ul">
  <% @accomodations.each do |accomodation| %>
    <li class="accomodations-li"><%= link_to accomodation.location, accomodation_path(accomodation.id) %></li>
    <div>
    <ul class="accomodations-ul">
      <li class="accomodations-li"><%= accomodation.description %></li>
      <li class="accomodations-li"><%= accomodation.price %></li>
      <li class="accomodations-li"><%= accomodation.rooms %></li>
    </ul>
    </div>
  <% end %>
</ul>

app/views/accomodations/show.html.erb
<div class="accomodation-show">
  <h3>Location</h3>
  <%= @accomodation.location %>
  <h3>Description</h3>
  <%= @accomodation.description %>
  <h3>Price</h3>
  <%= @accomodation.price %>
  <h3>Rooms</h3>
  <%= @accomodation.rooms %>
  <h3>Cancellation Fee</h3>
  <%= @accomodation.cancellation_fee %><br>

  <%= link_to "Book this room", new_booking_path %></br>
  <%= link_to "Back", :back %>
</div>

app/views/bookings/_form.html.erb
<%= form_for @booking do |f| %>
  <% if @booking.errors.any? %>
      <div class="error_messages">
        <h2 class="error">Form is invaid</h2>
        <ul>
          <% @booking.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="form-group"><%= f.label :check_in %><br />
  <%= f.text_field :check_in, autofocus: true %></div>

  <div class="form-group"><%= f.label :check_out %><br />
  <%= f.text_field :check_out, autofocus: true %></div>

  <div><%= f.submit "Book it now!", :class => "btn btn-default" %></div>
<% end %>

app/views/bookings/new.html.erb
<h1>Booking room</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Airbnb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_url%></li>
        <li><a href="#">Why Airbnb?</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Profile", user_path(current_user.id) %></li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <input type="text" class="form-control col-lg-8" placeholder="Search">
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> Logged in as <strong><%= current_user.email %></strong>.</li>
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="container-full">

        <div class="row">

          <div class="col-lg-12 text-center v-center">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <%= yield %>

            <br><br><br>

          </div>

        </div> <!-- /row -->

        <div class="row">

          <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
            <a href="#"><i class="icon-google-plus"></i></a> <a href="#"><i class="icon-facebook"></i></a>  <a href="#"><i class="icon-twitter"></i></a> <a href="#"><i class="icon-github"></i></a> <a href="#"><i class="icon-pinterest"></i></a>
          </div>

        </div>

  </div> <!-- /container full -->


</body>
</html>

app/views/users/show.html.erb
<h1>Hello <%= current_user.name %></h1>
<div class="row">
  <div class="col-md-12">
    <div class="col-sm-6">
      <%= render './accomodations/form' %>
    </div>
    <div class="col-sm-6">
      <div class="accomodation-list">
        <%= render @accomodations %>
      </div>
    </div>
  </div>
</div>